# Copyright (C) 2026 Gregory R. Warnes
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# This file is part of CV-Builder.
# For commercial licensing, contact greg@warnes-innovations.com

"""Unit tests for scripts/extract_specstory_audit.py."""

from __future__ import annotations

import io
import json
import runpy
import tempfile
import unittest
from contextlib import redirect_stderr, redirect_stdout
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SCRIPT_PATH = ROOT / 'scripts' / 'extract_specstory_audit.py'


class TestExtractSpecstoryAuditCli(unittest.TestCase):

    def test_build_report_extracts_session_metadata(self):
        script_module = runpy.run_path(str(SCRIPT_PATH))
        build_report = script_module['build_report']

        with tempfile.TemporaryDirectory() as tmpdir:
            history_dir = Path(tmpdir)
            (history_dir / '2026-03-01_demo.md').write_text(
                '<!-- Generated by SpecStory, Markdown v2.1.0 -->\n'
                '<!-- Demo Session '
                '123e4567-e89b-12d3-a456-426614174000 '
                '(Copilot) -->\n\n'
                '_**User (prompt)**_\n\n'
                'This session is being continued from a previous '
                'conversation\n\n'
                '1. Primary Request and Intent:\n'
                '- Finish the audit\n'
                '- Verify PR #66 and commit abc1234\n\n'
                '2. Key Technical Concepts:\n'
                '- SpecStory\n\n'
                '---\n\n'
                '_**Agent (reply)**_\n\n'
                'Looking at pull request #77 now.\n',
                encoding='utf-8',
            )

            report = build_report(history_dir)

            self.assertEqual(report['session_count'], 1)
            session = report['sessions'][0]
            self.assertEqual(session['file'], '2026-03-01_demo.md')
            self.assertEqual(
                session['session_id'],
                '123e4567-e89b-12d3-a456-426614174000',
            )
            self.assertTrue(session['continued'])
            self.assertEqual(
                session['first_user_line'],
                'This session is being continued from a previous conversation',
            )
            self.assertEqual(
                session['primary_requests'],
                ['- Finish the audit', '- Verify PR #66 and commit abc1234'],
            )
            self.assertEqual(session['prs'], ['66', '77'])
            self.assertEqual(session['commits'], ['abc1234'])

    def test_cli_writes_json_to_output_file(self):
        script_module = runpy.run_path(str(SCRIPT_PATH))
        main = script_module['main']

        with tempfile.TemporaryDirectory() as tmpdir:
            history_dir = Path(tmpdir) / 'history'
            history_dir.mkdir()
            output_path = Path(tmpdir) / 'audit.json'
            (history_dir / '2026-03-02_demo.md').write_text(
                '_**User (prompt)**_\n\n'
                'Audit this repo.\n\n'
                '---\n\n'
                '_**Agent (reply)**_\n\n'
                'Done.\n',
                encoding='utf-8',
            )

            stdout = io.StringIO()
            stderr = io.StringIO()
            with redirect_stdout(stdout), redirect_stderr(stderr):
                exit_code = main([
                    '--history-dir', str(history_dir),
                    '--output', str(output_path),
                ])

            self.assertEqual(exit_code, 0)
            self.assertEqual(stdout.getvalue(), '')
            self.assertIn('Wrote 1 sessions to', stderr.getvalue())

            payload = json.loads(output_path.read_text(encoding='utf-8'))
            self.assertEqual(payload['session_count'], 1)
            self.assertEqual(
                payload['sessions'][0]['first_user_line'],
                'Audit this repo.',
            )


if __name__ == '__main__':
    unittest.main()
